# Generated by Django 3.1.4 on 2023-02-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=300)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.TextField(max_length=1000)),
                ('used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serverAPI.user')),
            ],
        ),
    ]
