# Generated by Django 3.1.4 on 2023-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0003_auto_20230203_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelroute',
            name='way',
            field=models.ManyToManyField(blank=True, to='serverAPI.PointOfInterest'),
        ),
    ]
