# Generated by Django 4.1.6 on 2023-02-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0005_travelroute_time_travelroute_way_len'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='way_len',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
