# Generated by Django 3.1.4 on 2023-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverAPI', '0005_travelroute_time_travelroute_way_len'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(blank=True)),
                ('way_len', models.IntegerField(blank=True)),
                ('way', models.ManyToManyField(blank=True, to='serverAPI.PointOfInterest')),
            ],
        ),
    ]
